#[theme]
#base="dark"
#primaryColor="#0145AC"
#backgroundColor="#F2F2F2"
#secondaryBackgroundColor="#e2e4e9"
#textColor="#292F39"
#font="sans serif"


[theme]
base="dark"
primaryColor="#3296e3"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="##5c729e"
textColor="#262730"
font="sans serif"