#[theme]
#base="dark"
#primaryColor="#0145AC"
#backgroundColor="#F2F2F2"
#secondaryBackgroundColor="#e2e4e9"
#textColor="#292F39"
#font="sans serif"


[theme]
base="light"
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"